[4.165s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 59, in build
    available_commands = await self._get_available_commands(
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 142, in _get_available_commands
    output = await check_output(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/python3', 'setup.py', '--help-commands'] to pass: Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 19, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.8/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3268, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3251, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3303, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 622, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2074, in find_on_path
    path_item_entries = _by_version_descending(filtered)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2044, in _by_version_descending
    return sorted(names, key=_by_version, reverse=True)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2040, in _by_version
    name, ext = os.path.splitext(name)
  File "/usr/lib/python3.8/posixpath.py", line 125, in splitext
    return genericpath._splitext(p, sep, None, extsep)
  File "/usr/lib/python3.8/genericpath.py", line 137, in _splitext
    while filenameIndex < dotIndex:
KeyboardInterrupt

